- Cargo.lock
- tree/Cargo.toml
- tree/src/ls.rs
- tree/src/ls_util/entry.rs
- tree/src/ls_util/mod.rs
- tree/src/ls_util/utf8_lossy.rs
- tree/tests/integration.rs
- tree/tests/ls/tmp/.gitignore
This passes all of coreutils ls' [tests](https://github.com/coreutils/coreutils/tree/master/tests/ls) excluding non-POSIX ones.
Two tests have quirks though:
- `test_ls_file_type` skips block/character devices if not run with `sudo -E cargo ...`. Those need elevated permission to create.
- `test_ls_time` will stall a bit because it needs to wait for the ctime of the file to change. This is already an improvement over the 4 second wait time of the original.
There's also the `-k` option which coreutils always has enabled. Specification says to use 512-byte blocks if `-k` isn't specified but they always have it as 1024-byte blocks with or without `-k`.
> ls implementation

- tree/Cargo.toml
- tree/src/mv.rs
- tree/tests/integration.rs
- tree/tests/mv/mod.rs
This pretty much has max compatibility with GNU coreutils mv even down to the error messages.
There's 3 tests locked under the `posixutils_test_all` feature flag:
- `test_mv_hardlink_case` - Needs a case-insensitive filesystem that can support hard links. It's hard to do it dynamically so it must be supplied through an env var, `CASE_INSENSITIVE_TMPDIR`
- `test_mv_i_link_no` - This requires [script](https://www.man7.org/linux/man-pages/man1/script.1.html) to fake tty
- `test_mv_sticky_to_xpart` - Needs root, a username in `NON_ROOT_USERNAME` and must not be run together with other tests
I experimented enabling the `posixutils_test_all` feature dynamically based on an environment variable using a build script like in this [method](https://github.com/rust-lang/cargo/issues/5499) but it …
> `mv` fixes and tests

- xform/src/lzw.rs
- xform/src/uncompress.rs
btw this wasn't an assigned task, i was curious on the uncompress and it seems it didn't read upto EOF with those dynamic code size(i.e n_bits), So this fixes it and i also added some comments, there were a lot of bitwise operation, so i thought it needed some comments
> fix: read upto EOF in uncompress

- tree/tests/cp/mod.rs
- tree/tests/integration.rs
Hopefully fixes #101.
~~I'm assuming it's related to [this](https://www.mail-archive.com/bug-cpio@gnu.org/msg00128.html). Solution was to work with the fd directly instead of passing the path to the chmod, et al.~~
I was able to replicate #101 by removing the `libc::umask` call in `test_cp_perm`. That implies it was not being set properly perhaps due to `test_cp_existing_perm_dir` running its own umask call at the same time. This PR prevents `test_cp_perm` and `test_cp_existing_perm_dir` from running simultaneously.
> Fix possible race condition in cp

- text/Cargo.toml
- text/src/uniq.rs
- text/tests/integration.rs
> First implementation of uniq

- tree/tests/cp/mod.rs
- tree/tests/integration.rs
- tree/tests/integration2.rs
- tree/tests/rm/mod.rs
#112 and #102.
There should no longer be any multithreading race with `umask` since this would make them run on a separate test process.
The documentation says using multiple integration test binaries is [less efficient](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#integration-tests) but it seems unavoidable in this case.
> Isolate umask callers to a separate process

- tree/src/common/mod.rs
This coincidentally fixes #118.
Noticed the bug after testing coreutils `rm` on `test_rm_rm3` with umask 0002.
> Fix file writability check

- Cargo.lock
- Cargo.toml
- gettext-rs/Cargo.toml
- gettext-rs/README.md
- gettext-rs/src/lib.rs
A temporary fix for failing build on macos https://github.com/rustcoreutils/posixutils-rs/actions/runs/10173778299/job/28138428272 which is highly likely to be related to https://github.com/gettext-rs/gettext-rs/issues/121
A long term resolution will likely involve one of the following:
a) Wait for https://github.com/gettext-rs/gettext-rs/pull/119 to get merged, and then fix the breaking changes introduced by https://github.com/dennisschagt/gettext-rs/commit/ec1aad1cbd167f56e6915c379c59d199a54c2758
b) Use https://docs.rs/gettext/0.4.0/gettext/ instead accepting its limitations and it's apparent abandonment.
c) Fork `gettext-rs`.
d) Replace gettext entirely with a more modern localization system.  https://github.com/unicode-org/message-format-wg  is still in the works, and so something …
> Create a mock for gettext-rs in order to fix the failing build on macos

- awk/src/interpreter/mod.rs
> awk: fix srand builtin function

- text/diff.rs
- text/diff_util/constants.rs
- text/diff_util/diff_exit_status.rs
- text/tests/diff-tests.rs
Introduces a megaton of new warnings into the build.
Reverts rustcoreutils/posixutils-rs#208
> Revert "diff: exit with correct status"

- text/paste.rs
- text/tests/grep/mod.rs
- text/tests/paste/mod.rs
Allow an empty delimiter list, so the program can do something useful in this case, instead of just exiting. Also, some other implementations of `paste` permit this use case, and users of paste rely on this functionality. [1] Also, read from stdin if "-" is passed.
[1] https://stackoverflow.com/questions/1251999/how-can-i-replace-each-newline-n-with-a-space-using-sed/7697604#7697604
> paste: allow empty -d, and stdin

- text/paste.rs
- text/tests/paste/mod.rs
Multiple stdin ("-") inputs were causing a deadlock, since stdin was locked when processing the first occurrence.
Also: fix a couple other bugs in paste, and add tests for them.
> paste: allow multiple stdin inputs

- Cargo.lock
- m4/Cargo.toml
- plib/Cargo.toml
- plib/src/lib.rs
- plib/src/priority.rs
- process/Cargo.toml
- process/renice.rs
> Musl merge: priority APIs

- Cargo.lock
- Cargo.toml
- file/Cargo.toml
- misc/Cargo.toml
- process/Cargo.toml
- process/nohup.rs
- text/Cargo.toml
- tree/Cargo.toml
- tree/mv.rs
- tree/rm.rs
- tree/tests/mv/mod.rs
- users/Cargo.toml
- users/mesg.rs
- users/tty.rs
small code change for a trait from std. it has MSRV 1.70.0
P.S. when I run clippy I've got too much warnings and even errors. I can help with it and apply fixes for all of them
> feat: use `std::io::IsTerminal` instead of `atty` crate

- text/wc.rs
As suggested in #137, I took inspiration from [wc2](https://github.com/robertdavidgraham/wc2) to improve wc_file_bytes.
In my benchmarks (tested with 1G utf8.txt file generated with [wctool](https://github.com/robertdavidgraham/wc2/blob/master/wctool.c)), it is a bit faster than wc2, and on par with [wz](https://github.com/Altair-Bueno/wz), except when passing multiple files as argument because wz will parallelize computation, but I guess we don't want to pull rayon as a dependency here :)
> Improve wc

- text/wc.rs
On my machine, time decreased by 75% on 1Gb utf8.txt, from 7.4s to 1.85s.
> [wc] faster character count

- ftw/src/dir.rs
- ftw/src/lib.rs
- ftw/tests/integration.rs
- ftw/tests/integration2.rs
- tree/common/mod.rs
- tree/ls.rs
- tree/ls_util/entry.rs
- tree/mv.rs
- tree/rm.rs
Had to modify `ftw` quite a bit to accommodate the required directory listing order for `ls`. This PR modified more files than necessary because of the need to add new options to `ftw::traverse_directory` - I used the struct update syntax to hopefully avoid needing to do it again in the future if more options are added:
```rust
ftw::TraverseDirectoryOpts {
list_contents_first: true,
..Default::default() // Sets the other options to their default values
},
```
Also fixed clippy errors on the modified files while I was at it.
> Port ls to ftw

- fs/df.rs
- fs/mntent.rs
- fs/tests/mtab.txt
I don't have a machine with Mac OS, so please someone check it.
> fs: Add mntent.h wrapper

- file/file.rs
- text/diff.rs
- text/diff_util/common.rs
- text/diff_util/dir_data.rs
- text/diff_util/dir_diff.rs
- text/diff_util/file_diff.rs
> Fix clippy::manual_map, clippy::redundant_field_names and remove one panic

- text/tests/tr/mod.rs
- text/tr.rs
> tr: Add support for octal sequences

- file/tests/od/mod.rs
- text/paste.rs
- text/tests/paste/mod.rs
- text/tests/paste/output_paste_custom_delimiters.txt
- text/tests/paste/output_paste_custom_delimiters_serial.txt
- Implement handling of "\0" delimiter
- Process data in bytes to allow handling of non-UTF-8 data
- Forbid unescaped trailing backslash delimiter
- Fix handling of repeated input files
- In "-s" mode, reset delimiters iterator after each file
> paste: fix multiple bugs

- file/split.rs
Also returned assert!(false); in `fn write()`
> split: impl struct Suffix and add tests

- text/tests/tr/mod.rs
- text/tr.rs
tr currently only handles ranges if they are the only construct in
the string containing them (see `contains_single_range`).
Add proper handling of ranges: multiple in one string, ranges from
one character type to another (e.g. tr -d '\060-9 A-Z').
Fix handling of octal sequences above \377.
Add validation to ensure equiv (in "[=equiv=]" constructs) is only
one character.
Add validation to ensure ranges are not "backwards" (the ending
character be must greater than or equal to the starting character).
Parse and validate string1 and string2 before reading from stdin.
> tr: add full support for ranges

- Cargo.toml
- file/file.rs
- fs/df.rs
- m4/tests/integration_test.rs
- text/tests/join/mod.rs
- text/tests/pr/mod.rs
- tree/tests/cp/mod.rs
- tree/tests/mv/mod.rs
- tree/tests/rm/mod.rs
Add result of auto-fixing with:
"cargo clippy --fix -- --allow 'clippy::all' --deny 'clippy::needless_borrow'"
> Add "needless_borrow" lint

- text/tail.rs
- text/tests/tail/mod.rs
Also: fix -c 0 and -n 0 bug
Also: add some simple optimizations
> tail: handle non-UTF-8 input in -n mode

- display/printf.rs
- text/tr.rs
Also: allow non-UTF-8 data in arguments
Also: add handling of "\c"
> printf: handle hexadecimal and octal escapes

- tree/chgrp.rs
- tree/tests/chgrp/mod.rs
This PR finalizes the chgrp implementation and includes tests for it.
I found an undocumented quirk regarding passing a missing `group` argument to chgrp that's neither mentioned in the man page nor in the specification. Supposedly,
```sh
chgrp '' a
```
Should change `a`'s ctime but shouldn't modify its group. I think the behavior was taken from chown based on its man page. I added it in because it seems like a common pattern seeing that it's even on Rust's [chown](https://doc.rust-lang.org/stable/std/os/unix/fs/fn.chown.html).
> Finish chgrp

- tree/tests/tree-tests.rs
I think I missed this file during the rebase. My apologies for the oversight.
> Add missing chgrp module in tree-tests.rs

- tree/tests/chgrp/mod.rs
On Linux systems, the chgrp tests expect the test runner to be a member of the adm group. This commit changes that to attempt to dynamically identify a suitable secondary group to use in the tests, or error out if one cannot be identified.
On my system, this was the cause of all of the test failures outline in #377.
> More resilient secondary group selection for chgrp tests

- datetime/cal.rs
> cal: start-of-month display fixes
